### ISSUE TITLE
OpenId  vs Mobile Number 

### ISSUE THREAD

**Issue by iamdatanick** [camaraproject/IdentityAndConsentManagement#11]
Why would you plug into a third party ID provider?

when essentially with telco you have the optimal top-level Identifier which is a mobile number. 

You run into PII problems when you later in an email. Email + Mobile Numb = PII

mobile Number ALONE is an extremely strong solution. 

why would telco use an email based ID graph which had been proven to be broken historically. 

Look at how many emails people have historically? 

How often do humans change people change personal number. 

This should be a telco solution not a big tech provider solution. 

Open to help doing the mobile number. Currently working on aggregation of data for GLTTR project.

**Comment by jpengar** [comment]
@NickVenezi Sorry, but I don't understand your point. I must be missing something... but OpenID only refers to the OpenID Connect (OIDC) standard (https://openid.net/connect/).

OpenID Connect (OIDC) is an identity layer built on top of the OAuth 2.0 framework, which is the industry standard protocol framework for authorisation. OIDC allows applications to verify a user's identity and retrieve basic profile information. And what the presentation slides say is that the proposed solution must follow the OIDC standard, which is the de facto standard for handling authentication.

**Comment by jordonezlucena** [comment]
In the conf. call we had two weeks ago, it was noted that Open ID (formally speaking is Open ID Connect, i.e. OIDC) aND Mobile Number refer to different concepts positioned at different planes, so it is not 'either...or' approach . @jpengar in the comment above is in that direction.  
@iamdatanick: let us know whether it's clear or there are further concerns you want to raise.

**Comment by iamdatanick** [comment]
Why would you want to enhance someone else framework which would allow for leakage of data.

Open ID has resellers.

Sent from my iPhone

On May 9, 2023, at 6:38 AM, Jose Ordonez-Lucena ***@***.***> wrote:

﻿

In the conf. call we had two weeks ago, it was noted that Open ID (formally speaking is Open ID Connect, i.e. OIDC) aND Mobile Number refer to different concepts positioned at different planes, so it is not 'either...or' approach . @jpengar<https://github.com/jpengar> in the comment above is in that direction.
@iamdatanick<https://github.com/iamdatanick>: let us know whether it's clear or there are further concerns you want to raise.

**Comment by jpengar** [comment]
The use of OAuth 2.0 and OIDC (OpenID Connect) has been previously agreed by the CAMARA participants and is aligned with the CAMARA AuthN/AuthZ commonalities https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md.

**Comment by jpengar** [comment]
I suggest to close this issue as discussed in the last conference call. CC @rartych

**Comment by iamdatanick** [comment]
Open ID and OAuth is based on faulty tech from the early 2000s

Over 1B accounts have been created with the Open ID framework, using OpenID as a  solution will have duplication.

Accounts will be connected to a non-relevant historical user accounts. 


I am happy to get on a call and discuss further.
