### ISSUE TITLE
Broken link in v0.1 of CAMARA-API-access-and-user-consent.md

### ISSUE THREAD

**Issue by hdamker** [camaraproject/IdentityAndConsentManagement#139]
**Problem description**

https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-API-access-and-user-consent.md points to https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-AuthN-AuthZ-Concept.md in `main` branch which was deleted after the release of v0.1.

**Expected behavior**

Bring https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-AuthN-AuthZ-Concept.md back into `main` but with a disclaimer that the document is deprecated and will be deleted after ICM v0.2 *and* Commonalities v0.4 are released. 

This approach would also address https://github.com/camaraproject/Commonalities/issues/167

**Alternative solution**

Patch the link within v0.1.x of ICM with the correct link to https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-AuthN-AuthZ-Concept.md

**Additional context**

**Comment by jpengar** [comment]
As I said in the SP-ICM 2024-03-13 meeting (sorry, I thought it was updated in the issue as a comment), I'm actually fine with both options, either the proposed solution or the alternative.

**Comment by hdamker** [comment]
Learning from this issue: references to documents should always be links to a released version, not to main. In case the documents are released together, the links need to be updated latest within the release PR.
