### ISSUE TITLE
Create ICM Release Plan

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/IdentityAndConsentManagement#146]
**Problem description**
TSC asked ICM to create a release plan 

https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24
![image](https://github.com/camaraproject/IdentityAndConsentManagement/assets/1721863/8cf1b580-eb28-494b-917b-d6648f47d5be)

**Expected action**
e.g. Label issues or create a icm-release-plan-document.md

**Comment by jpengar** [comment]
I think we can use this issue as a way to agree the scope of the release and proceed as done in Commonalities in https://github.com/camaraproject/Commonalities/issues/175

**Comment by jpengar** [comment]
As agreed in the [08/05 WG call](https://wiki.camaraproject.org/pages/viewpage.action?pageId=25297359), we are using the `v0.2-candidate` tag to mark issues to be addressed in the Fall24 meta-release. A new tag `ICM-backlog` has been created to mark other issues that remain in the WG backlog. So far, the list of issues/PRs to be resolved within Fall24 meta-release are:

* #95 >> I think this one could be closed by #121 which removes "API level" scope...
* #100 
* #121 
* #128 
* #131
* #138
* #143
* #148

**Comment by hdamker** [comment]
Added the link to this issue to https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24.
(and took the freedom to replace "tag" with "label" in the above comments).

**Comment by jpengar** [comment]
Added #154 & #155 to the list of issues/PRs to be resolved within Fall24 meta-release.

**Comment by jpengar** [comment]
Added #156 and #159 to the list of issues/PRs to be resolved within Fall24 meta-release.

**Comment by jpengar** [comment]
Added #162 which fixed #159 to the list of issues/PRs to be resolved within Fall24 meta-release: https://github.com/camaraproject/IdentityAndConsentManagement/issues/146#issuecomment-2100969538

**Comment by jpengar** [comment]
Added #170 to the list of issues/PRs to be resolved within Fall24 meta-release: https://github.com/camaraproject/IdentityAndConsentManagement/issues/146#issuecomment-2100969538

**Comment by AxelNennker** [comment]
I think we need a PR for https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/CHANGELOG.md and document what our documents are etc.
Would @jpengar or @sebdewet please create that PR because I am on vacation starting next Monday.

**Comment by jpengar** [comment]
If I understand your point correctly, CHANGELOG should be edited as part of the v0.2.0 release (i.e. FAll24 meta-release), as it was when the v0.1.0 release was generated. We can do that during your holidays, no problem.

**Comment by jpengar** [comment]
Meta-release scope is now 100% covered. Thanks everyone!

**Comment by jpengar** [comment]
https://github.com/camaraproject/IdentityAndConsentManagement/pull/177 is ready to review for release 0.2.0-rc creation. @AxelNennker @sebdewet @Elisabeth-Ericsson @garciasolero @hdamker @shilpa-padgaonkar @diegogonmar @bigludo7 @mhfoo et all

**Comment by jpengar** [comment]
#177 is MERGED and v0.2.0-rc.1 created https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/v0.2.0-rc.1

**Comment by jpengar** [comment]
https://github.com/camaraproject/IdentityAndConsentManagement/pull/179 README update for v0.2.0-rc.1 pre-release

**Comment by AxelNennker** [comment]
Create rc.2 with bug fixes.

**Comment by hdamker** [comment]
> Create rc.2 with bug fixes.

One bug which I have introduced is the release tag. It should have r0.2.0-rc.1 instead of v0.2.0-rc.1 (cf https://github.com/camaraproject/ReleaseManagement/issues/41). So let's use the next release candidate and create it correctly as r0.2.0-rc.2.

**Comment by jpengar** [comment]
> > Create rc.2 with bug fixes.
> 
> One bug which I have introduced is the release tag. It should have r0.2.0-rc.1 instead of v0.2.0-rc.1 (cf [camaraproject/ReleaseManagement#41](https://github.com/camaraproject/ReleaseManagement/issues/41)). So let's use the next release candidate and create it correctly as r0.2.0-rc.2.

@hdamker Yes, we discussed this in the last WG call, and we agree to fix it in the next release candidate, expected next Friday. I will add this to the meeting notes for the record.

**Comment by jpengar** [comment]
PR https://github.com/camaraproject/IdentityAndConsentManagement/pull/181 to generate ICM release `r0.2.0-rc.2` is ready for review. FYI.
CC @hdamker

**Comment by jpengar** [comment]
`r0.2.0-rc.2` release created https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r0.2.0-rc.2

**Comment by jpengar** [comment]
@camaraproject/release-management_maintainers Should we proceed to create the PR for the public release of 0.2.0 as is being also raised in https://github.com/camaraproject/Commonalities/issues/282??

I would like to discuss how to proceed with creating the ICM public release so that other backlogged PRs can be addressed.

CC @AxelNennker @sebdewet @rartych

**Comment by hdamker** [comment]
@jpengar sorry for the late answer, it went through the cracks. 

We discuss today in Release Management call that Commonalities and ICM should have their PRs for the public releases ready before the TSC on Thursday afternoon. Preferable already with some Codeowner approvals, so that the TSC can "approve" the releases and it can get created (it should be done before the Sub Project are doing their public releases).

As this is more a formal thing I hope that is possible?

If there are later bugfix releases 0.2.x needed, they will done in a maintenance branch which starts in r0.2.0. Which means that after the public release of 0.2.0 end of the week the main branch is free to continue with the work for the next release cycle.

CC @AxelNennker @sebdewet @rartych

**Comment by jpengar** [comment]
https://github.com/camaraproject/IdentityAndConsentManagement/pull/192 PR for the public release of ICM 0.2.0 is ready for review. @AxelNennker @sebdewet @hdamker @camaraproject/release-management_maintainers

**Comment by jpengar** [comment]
Public release `r0.2.0` is available at https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r0.2.0

**Comment by AxelNennker** [comment]
As per discussion in the wg meeting today
