### ISSUE TITLE
"CAMARA-API-access-and-user-consent.md" aligment with last decisions made in profile doc

### ISSUE THREAD

**Issue by jpengar** [camaraproject/IdentityAndConsentManagement#154]
**Problem description**

As raised in the 08/05 WG meeting, it is required to align `CAMARA-API-access-and-user-consent.md` document with the last decisions made in the `CAMARA-Security-Interoperability.md` profile document. Mainly related to the purpose management solution agreed in the profile.

**Expected action**

Clean up and update the `CAMARA-API-access-and-user-consent.md` document to reflect the latest profile decisions and/or to include references(*) to the new profile document where appropriate.

**Additional context**

(*)**NOTE: These references need to be updated before the next release generation to change the path according to the next release tag. To avoid problems with broken links we had in the past**.

**Comment by jpengar** [comment]
Already working on PR...

**Comment by hdamker** [comment]
> Already working on PR...

Thanks @jpengar ... have assigned the issue to show this clearly.

**Comment by AxelNennker** [comment]
I suggest moving the OpenAPI security scheme "openid" from CAMARA-API-access-and-user-consent.md Commonalities API design guidelines because the API design guideline already have a [section](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#11-definition-in-openapi) that describe how a Camara API should be in OpenAPI. 

Please see: https://github.com/camaraproject/Commonalities/pull/208

**Comment by jpengar** [comment]
> I suggest moving the OpenAPI security scheme "openid" from CAMARA-API-access-and-user-consent.md Commonalities API design guidelines because the API design guideline already have a [section](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#11-definition-in-openapi) that describe how a Camara API should be in OpenAPI.
> 
> Please see: [camaraproject/Commonalities#208](https://github.com/camaraproject/Commonalities/pull/208)

I would keep the discussion here tied to the original goal of the issue, and deal with this other topic you raise above in a separate issue (independent of #154 and PR #155). And I would keep https://github.com/camaraproject/Commonalities/pull/208 in DRAFT until a decision is made in the ICM WG. ICM, as Commonalities WG, also provides guidance to API subprojects and this should be well-known. This particular guideline comes from ICM and I personally would keep this information within ICM.
