### ISSUE TITLE
Explain or remove "3-legged" in CAMARA APIs access and user consent management

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/IdentityAndConsentManagement#159]
**Problem description**
[CAMARA APIs access and user consent management](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md) uses the term `3-legged` and `3-legged access token`.
Those terms are not defined.

**Expected action**
Define or replace the term(s)

Additional Context

https://github.com/search?q=org%3Acamaraproject+3-legged&type=code

**Comment by jpengar** [comment]
Would it be ok with you to add the definition of those terms in [Glossary of Terms and Concepts](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#glossary-of-terms-and-concepts) section? Do you think it would solve the problem?

**Comment by jpengar** [comment]
I've created https://github.com/camaraproject/IdentityAndConsentManagement/pull/162 to fix this issue. @AxelNennker Could you check if it is ok with you?
