### ISSUE TITLE
Use of term NaaS

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/IdentityAndConsentManagement#17]
IMHO the term NaaS is used in different contexts across different organizations (at least amongst operators). I would propose to remove this term from README and the PR doc https://github.com/camaraproject/IdentityAndConsentManagement/pull/13 and use only the term operator platform where absolutely necessary.

**Comment by jpengar** [comment]
Resolved in https://github.com/camaraproject/IdentityAndConsentManagement/pull/13#discussion_r1176222110. Fixed in commit https://github.com/camaraproject/IdentityAndConsentManagement/commit/150a596f77633aa771dbadbebf6bc00b107a5762

**Comment by jpengar** [comment]
My last commit https://github.com/camaraproject/IdentityAndConsentManagement/pull/13/commits/4b761353f33ee263e98e8309c8fb698908401206 also fixes README file.

**Comment by jpengar** [comment]
I think this issue is very straightforward and should be fixed by now. So I'm going to close it. However, when you come back @shilpa-padgaonkar, if you have any further comments, it could be reopened if necessary.
