### ISSUE TITLE
The wording in the Mandatory template for info.description is unclear

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/IdentityAndConsentManagement#178]
**Problem description**

The wording in the Mandatory template for info.description is unclear.

```
Which specific authorization flows are to be used will be determined during onboarding process, happening between the API Client and the Telco Operator exposing the API, taking into account the declared purpose for accessing the API, while also being subject to the prevailing legal framework dictated by local legislation.
```

**Expected behavior**
At a minimum add a `the` before onboarding process or use the plural `onboarding processes` if that was the intent.

```diff
- during onboarding process
+ during the onboarding process
```

**Alternative solution**

Alternately, split this into two sentences.

"The specific authorization flows to be used will be determined during the onboarding process between the API client and the Telco operator exposing the API. This determination will consider the declared purpose for accessing the API and be subject to the prevailing legal framework dictated by local legislation."

**Additional context**

We've added this Mandatory text to QoD and it isn't clear.

I'm happy to create a PR and discuss further.

**Comment by AxelNennker** [comment]
During the ICM meeting on 17. July we decided to change info.description after the release
