### ISSUE TITLE
Replace internal links between ICM documents with relative links to stay within the same release tree / fork / release package

### ISSUE THREAD

**Issue by hdamker** [camaraproject/IdentityAndConsentManagement#187]
**Problem description**

documentation/CAMARA-API-access-and-user-consent.md contains about six links to the Profile document which are written as fully qualified URLs which are pointing to the main branch of ICM. The Profile contains one such link which points to [documentation/CAMARA-API-access-and-user-consent.md](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md)

A reader within a release tree would jump out of the tree into a potential wrong version. The same for someone who has downloaded the release package (zip-file) of ICM.

**Expected behavior**

Use - as [recommend](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links) by GitHub - relative links instead, concrete with the following replacements:
`https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-Security-Interoperability.md` to be replace with `CAMARA-Security-Interoperability.md`
`https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md` to be replaced with `CAMARA-API-access-and-user-consent.md`

**Alternative solution**

**Additional context**

**Comment by hdamker** [comment]
@jpengar @AxelNennker If you agree, could someone of you take the PR for this issue?

**Comment by jpengar** [comment]
Let's talk about it in Today's call. I could easily do it in #181.

**Comment by hdamker** [comment]
It would be cleaner to do it in a short separate PR ... otherwise you have no PR you can mention in the Changelog ;-)

**Comment by jpengar** [comment]
> It would be cleaner to do it in a short separate PR ... otherwise you have no PR you can mention in the Changelog ;-)

xD I can do that too
