### ISSUE TITLE
ICM text should not state that `Telco Operators` are the ones providing these APIs

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/IdentityAndConsentManagement#190]
**Problem description**

Assuming that only "Telco Operators" will implement these APIs is not valid, since MSO and other none "Telco" operators will implement many of these APIs.

Per commonalities [reduce telco-specific terms](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#25-reduce-telco-specific-terminology-in-api-definitions)

Additional references to telcos in the documentation should also be removed
 
**Expected behavior**

Use network operator or service provider rather than telco / telco operator

**Alternative solution**

**Additional context**

This will cause confusion with the mandatory text, since MSOs who are not Telco's are planning to deploy and are contributing to CAMARA

**Comment by jpengar** [comment]
@RandyLevensalor  I see your point and tend to agree with you. If the WG agrees, the documentation could be adjusted accordingly. 

Regarding the [reduce telco-specific terms](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#25-reduce-telco-specific-terminology-in-api-definitions) Commonalities guidelines, I think they are actually more intended to make API specifications more developer friendly, who might not be familiar with some operator/network specific terms (and not specifically to "telco" term itself, which may be included as well). 

Having said that, I think there is actually a more fundamental "problem" with CAMARA and the references to "Telco". You could take a look at https://camaraproject.org/ for example (see pictures below).

**I see this as a broader topic not really specific to ICM and of course not specific to the mandatory `info.description` ICM template*. So far ICM is aligned with CAMARA*

<img width="827" alt="image" src="https://github.com/user-attachments/assets/5d408f00-2a5c-4b54-a183-07e755f92b3a">

![image](https://github.com/user-attachments/assets/2c178390-f93e-4d02-8d96-7fed3653456f)

**Comment by RandyLevensalor** [comment]
@jpengar Thanks for looking into this.  While this isn't the only instance of Telco being used, it's also referenced extensively in commonalities.

IMHO, the ICM is the highest priority, since it's a part of the mandatory text in the api specifications.  The others are marketing and internal documentation and are not a part of the actual APIs.

The marketing and internal documentation also need to be resolved.  And I'm sure that we'll find additional instances.
