### ISSUE TITLE
Integration to on device application (EAP-AKA) - ICM 3.0 Scope?

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/IdentityAndConsentManagement#198]
**Problem description**
Comment raised during Number Verification meeting today (not only myself :) ) 

We have the following issue https://github.com/camaraproject/NumberVerification/issues/86 on Integration to on device application (EAP-AKA) opened for a long time.

We are wondering if this topic in general, and, precisely the impact on CAMARA flow(s) should be followed in ICM in the scope of ICM3.0.

**Possible evolution**

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
> Related to #145

Thanks @shilpa-padgaonkar 
I missed this one ... but my question stays: Should ve add#145 in https://github.com/camaraproject/IdentityAndConsentManagement/issues/193 ?

**Comment by jpengar** [comment]
Thanks Shilpa, this is exactly what I wanted to point out, this issue is related to #145 and #94. @bigludo7 if you (or Number Verification WG) want to consider this as a candidate for sprint25 (r0.3.0), you can suggest it in #193.

**Comment by bigludo7** [comment]
Thanks @shilpa-padgaonkar @jpengar 
I'm happy now that #145 is part of #193.
I close my issue.
Thanks for the clarification.
