### ISSUE TITLE
Clarification for authentication in the auth code flow in the Identity and consent management (r0.20.0-rc2) 

### ISSUE THREAD

**Issue by mingshiwork** [camaraproject/IdentityAndConsentManagement#199]
**Problem description/clarification needed**
In the Identity and consent management (r0.20.0-rc2) CAMARA Security and Interoperability Profile, 
https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0-rc.2/documentation/CAMARA-Security-Interoperability.md

It is mentioned in the section of “Client Authentication”, this CAMARA document allows one client authentication method, private_key_jwt.

While in the section of “OIDC Authorization Code Flow”, CAMARA RECOMMENDS PKCE for CSRF protection. CAMARA Authorization Servers SHOULD implement PKCE. If PKCE is not used by the Client then the CAMARA AZ must handle state and nonce as defined in OAuth2.

Looking at the “Authorization Code Flow (Frontend Flow)” defined in the “CAMARA APIs Access and User Consent Management”, it is not clear where the private_key_jwt and PKCE are used to secure the API flow. 
https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0-rc.2/documentation/CAMARA-API-access-and-user-consent.md

Question 1:  where the private_key_jwt will be used to authenticate API request, is it on step 11 in the sequence diagram? 
Queston 2: How should the PKCE be employed in the front-end auth code flow? Detail description will be appreciated. 

**Expected action**
Please help answer above questions to bring clarity to the documentation. 

**Additional context**

**Comment by jpengar** [comment]
@mingshiwork 

>In the Identity and consent management (r0.20.0-rc2) CAMARA Security and Interoperability Profile,
https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0-rc.2/documentation/CAMARA-Security-Interoperability.md

[ICM r0.2.0 public release](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r0.2.0) is available, please use it as reference instead of the previous release candidate versions: https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0/documentation/CAMARA-Security-Interoperability.md

>Question 1: where the private_key_jwt will be used to authenticate API request, is it on step 11 in the sequence diagram?
Queston 2: How should the PKCE be employed in the front-end auth code flow? Detail description will be appreciated.

Both private_key_jwt and PKCE (Proof Key for Code Exchange) are mechanisms used in OAuth 2.0 and OpenID Connect to enhance the security of authorization flows, but they serve different purposes and are typically used in different contexts. 

The private_key_jwt is a client authentication method as defined in https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication. It is used by clients to authenticate to the authorization server when using the token endpoint. **It is the only client authentication method allowed by CAMARA**. The client generates a JWT (JSON Web Token) which is signed with its private key. This signed JWT is sent to the authorization server to prove the identity of the client.

You may want to take a look at https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0/documentation/CAMARA-ICM-examples.md for some usage examples.

Instead, PKCE (Proof Key for Code Exchange by OAuth Public Clients) provides an additional layer of security for the authorization code flow, but it is unrelated to client authentication. PKCE is a mechanism used in the authorization code grant flow to prevent attacks such as authorization code interception, especially when dealing with public clients. The client generates a random code verifier and its corresponding code challenge (usually a hashed version of the verifier). These are used during the authorization and token exchange process to bind the authorization code to the original client request.See https://datatracker.ietf.org/doc/html/rfc7636 for more details.

CC @AxelNennker @sebdewet Please add any other comments you may have.

**Comment by AxelNennker** [comment]
> Question 1: where the private_key_jwt will be used to authenticate API request, is it on step 11 in the sequence diagram?

Yes.
OIDC defines the [Token Request](https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest) in the authorization code flow. Camara defines that the client authentication method is private_key_jwt.

> Question 2: How should the PKCE be employed in the front-end auth code flow? Detail description will be appreciated.

Please choose a library or SDK that supports PKCE and meets your other requirements. The OpenId Foundation maintains a list of certified tools. https://openid.net/developers/certified-openid-connect-implementations/
In general, do not implement an openid provider yourself. There are several opensource implementations for which you can also buy support. Please do your own research which best fits your needs.
In case you notice that Deutsche Telekom has its own implementation of an OpenId Provider and call my a hypocrite, let me state that Deutsche Telekom is a very early supporter of the OpenId Foundation and a member of [OIDF](https://openid.net/foundation/benefits-members/) for many years. We have a long history in participating in IAM standardization and our current end customer-facing OP was implemented before OIDC existed. We are also using other certified OPs in production but requirements change over time and an OP you picked some years ago might not be your choice today.

The same is true for mobile applications and relying party software. Pick an SDK that supports PKCE and fits your requirements.

Avoid implicit flow.
Read [OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics)
Have a look at the [Financial API Security Profile](https://openid.bitbucket.io/fapi/fapi-2_0-security-profile.html)

**Comment by yudaprama** [comment]
Hi @jpengar @AxelNennker , thank you for your response

Allow me to join the discussion, as both @mingshiwork  and I are currently working on the CAMARA integration. I believe @mingshiwork is confused about when to use **private_key_jwt** and when to use **PKCE**.

Please correct me @jpengar @AxelNennker :

OpenID Connect (OIDC) supports two authentication flows: **2-legged** and **3-legged**.
- CAMARA uses OIDC, and for **2-legged flows** (also known as client credentials or client authentication flow), CAMARA only allows the **private_key_jwt** method.
- For **3-legged flows** (also known as authorization code flow), CAMARA recommends using the **PKCE** method.

### When to use **2-legged** or **private_key_jwt**?
The term "2-legged" come from 2 legs, refers to a flow where only two parties are involved:
1. **Client**: An entity that needs to access resources from the resource server.
2. **Resource Server**: A server that stores resources and legally owns them.

In this scenario, you should use **private_key_jwt**.

GSMA uses this for authentication in Telco FInder, refer to this: https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/blob/main/Chapters/Chapter%2005.md#api-end-points

### When to use **3-legged** or **PKCE**?
The term "3-legged" come from 3 legs, refers to a flow where three parties are involved:
1. **Client**: An entity that needs to access resources from the resource server.
2. **Resource Server**: A server that stores resources but does not legally own them; it only stores the resources on behalf of the resource owner.
3. **Resource Owner**: The person who owns the resources stored on the resource server.

In this scenario, you should use **PKCE**.

### Authorization Process Using **PKCE**

In this case, the client must initiate user authorization by calling the `/authorize` endpoint with the following parameters:
- **client_id**: The unique identifier for the client application.
- **response_type**: Specifies the type of response expected from the authorization server. Value: `code` (indicating that the authorization code flow is being used, which will return an authorization code).
- **redirect_uri**: The URI where the user will be redirected after authorization. This URI must match one of the URIs registered with the client.
- **scope**: Defines the level of access the application is requesting. Multiple scopes are space-separated.
- **state**: A unique value to ensure that the authorization response is linked to the correct request. Example: `unique-state-value-3`.
- **code_challenge_method**: Specifies the method used for the Proof Key for Code Exchange (PKCE). The value `S256` indicates that the SHA-256 hash algorithm is used.
- **code_challenge**: A base64-encoded, URL-safe string representing the hashed `code_verifier`, which is later used to exchange the code for a token.

### Redirect After Successful Authentication and Consent

After the user successfully authenticates and grants consent, they are redirected to the specified **redirect URI** with query parameters, including the **authorization code** and **state**.

#### Query Parameters Breakdown:
- **code**: The authorization code that the client will use to exchange for an access token. This code is short-lived and must be used immediately.
- **scope**: The scopes that were granted during the authorization process. These scopes are space-separated and should match or be a subset of the requested scopes.
- **state**: The same state value that was sent in the original authorization request. This ensures the response corresponds to the correct request. Example: `unique-state-value-3`.

### Token Exchange Process

The client exchanges the authorization code for an access token by making a POST request to the `/token` endpoint. This request must include the **code**, **redirect URI**, **client ID**, and the **PKCE code_verifier**.

#### Parameters Breakdown:
- **grant_type**: Specifies the type of OAuth2 flow. In this case, it’s `authorization_code` to indicate that the client is exchanging an authorization code for tokens. Example: `authorization_code`.
- **code**: The authorization code received in the redirect URI after the user’s authorization.
- **redirect_uri**: The same **redirect_uri** that was used in the original authorization request. This ensures the request is coming from the same client that initiated the flow.
- **client_id**: The same client ID used in the request to `/authorize`.
- **code_verifier**: The original code verifier used to generate the **code_challenge** when making the request to `/authorize`.

**Comment by garciasolero** [comment]
@yudaprama and @mingshiwork,

I think there is some confusion about what authentication mechanisms are used and whether they are related to the number of legs of the flow being executed. 

PKCE is not a client authentication method, it was originally designed to mitigate code interception attacks in an authorization code flow.

In the CAMARA profile, for all server-to-server calls from the application backend, `private_key_jwt` is the only method for those endpoints that require authentication. For example, for the `token`, `bc-authorize`, `revocation` or `introspection` endpoints. There are only confidential clients.

This means that for the `token` endpoint call in the authorization code flow, `private_key_jwt` authentication is required, regardless of whether a PKCE `code_challenge` was used in the previous `authorize` call.

**Comment by yudaprama** [comment]
So, you're essentially mixing 2-legged with 3-legged flows. Is this based on the OIDC spec or is it your own custom specification? 

If you're creating a standard, please ensure that it aligns with common specifications. This will allow developers to build using libraries. If you create a standard using your own spec, it means development will have to be done from scratch, leading to significant development costs and time!

I propose to review and revise it to use the common specification in the OIDC spec, which is supported by libraries.

**Comment by mhfoo** [comment]
@yudaprama is your question on how to protect ans secure the /authorize endpoint?

**Comment by jpengar** [comment]
@mingshiwork @yudaprama Can we close this issue?
