### ISSUE TITLE
Definition of scenarios for consent management 

### ISSUE THREAD

**Issue by rartych** [camaraproject/IdentityAndConsentManagement#21]
**Problem description**
The need for Consent Management API is widely accepted. However, there are different approaches and requirements for this API.
There are also multiple scenarios for consent management.

**Expected action**
I propose to start with definition of scenarios for user consent use and management in CAMARA, that would help to elicit requirements and define API specification. It can be done in  additional section of the proposed baseline document or in a separate document  (such as User Story within documentation in some subprojects). The scenarios can start from simple offline granting and revoking consent by the user and online checking consent with CAMARA Service API call, and include more complex one when the consent is given just before CAMARA Service API call.
Scenarios should present actions and roles of all actors involved.
Description of high-level scenarios (without going into details of protocol flows) should also help legal teams analyze the proposed approach for consent management.

**Additional context**
Scenarios can be illustrated with Sequence Diagrams that can be created  using [Mermaid tool ](https://mermaid.js.org/) and [included directly in Github Markdown files](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/).

**Comment by jpengar** [comment]
PR #33 has been restored in https://github.com/camaraproject/IdentityAndConsentManagement/pull/74
