### ISSUE TITLE
 Update error codes and info.description template for device / phone number identifiers 

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/IdentityAndConsentManagement#234]
**Description**
In Commonalities there is a new PR that ICM should be aware of, I think.
https://github.com/camaraproject/Commonalities/pull/324

info.description changes are an ICM topic, I think.

Please review and comment in that PR.

@camaraproject/commonalities_maintainers

**Comment by jpengar** [comment]
Thank you, @AxelNennker. I have already been in contact with my TEF colleagues to follow up on this.

**Comment by jpengar** [comment]
https://github.com/camaraproject/Commonalities/pull/324 is now merged. I think we can close this issue.
