### ISSUE TITLE
Baseline - Introduction - feedback

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/IdentityAndConsentManagement#25]
**Problem description**
Several text edit suggestions on Baseline doc PR #13 Introduction section  

**Expected action**

1. ‘Operator platform’ may unintentionally refer to GSMAs “Operator Platform Group” and reader implying a specific implementation (i.e. Open Gateway).  In alignment with the architectural diagram, we can use “Exposure Gateway” instead.
2. "This means that an API...” instead we can be specific a “CAMARA API exposed to Capability Consumers.”
3. “Policy enforcement … access to a (set of) scopes” -- until this part Personal Information is used and there is no linkage to scope.  We can help reader if we put ‘Personal Information (PI) resources that are referred to as scope’.

**Additional context**
n/a

**Comment by jpengar** [comment]
Fixed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/13 commit https://github.com/camaraproject/IdentityAndConsentManagement/pull/13/commits/4b761353f33ee263e98e8309c8fb698908401206 
@gmuratk Please take a look.
