### ISSUE TITLE
Baseline - Purpose relationship with other key concepts - feedback

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/IdentityAndConsentManagement#27]
**Problem description**
Suggested text edits and question on Baseline #13 Purpose relationship with other key concepts

**Expected action**

1. We need to make it clear to readers that an API may have multiple paths (operations) providing access to different Personal Info resources.  Thus, consent may need to be collected at API/path level in order to avoid any bypass / unintentional leakage of PI resources.
2. “A purpose has associated a set of personal information scopes…” -- we can remove ‘a’
3. With the API roaming and consent exchange between operators in mind:
- Should there be a categories of PI scopes defined or is that going to be more up to local regulations?
- Should there be suggestion to commonalities group, to suggest/require each API family to map the Personal resources each API/path enable to, if such categories of PI scopes (previous bullet) is available?
4. “Scopes are assigned to an application, granting access to APIs and other resources” -- relationship diagram doesn’t show this.  It does support it via the next bullet that is “Purposes are assigned to applications” and given the previous statement “A purpose has associated set of personal information scopes.”
5. “APIs or resources covered by the assigned scopes” -- doesn’t seem to be necessary as scopes can’t be associated with Apps without a specific purpose.  Next bullet cover that

**Additional context**
n/a

**Comment by jpengar** [comment]
> We need to make it clear to readers that an API may have multiple paths (operations) providing access to different Personal Info resources. Thus, consent may need to be collected at API/path level in order to avoid any bypass / unintentional leakage of PI resources.

Each API operation could be protected with a different scope (if required). This way you can actually control which scopes are allowed for a particular purpose, and eventually have enough granularity to control access for each API operation. This is something that needs to be included in the API definition for each API operation, and should be analysed on a case-by-case basis.

> A purpose has associated a set of personal information scopes

Why? It is correct, isn't it? we may say "A purpose is associated with a set of personal information scopes..."... in any case please, feel free to add this simple suggestion directly in the PR itself. 

> With the API roaming and consent exchange between operators in mind:
>Should there be a categories of PI scopes defined or is that going to be more up to local regulations?
>Should there be suggestion to commonalities group, to suggest/require each API family to map the Personal resources each >API/path enable to, if such categories of PI scopes (previous bullet) is available?

As far as we can see, the HTTP API access to CAMARA API is not affected by the network roaming status. In the sense that the API request is always sent to the "home" operator (i.e. the operator to which the user belongs). And the "home" operator could validate the consent and forward the request to the API server and so on... If that is what you mean.

> “Scopes are assigned to an application, granting access to APIs and other resources” -- relationship diagram doesn’t show this. It does support it via the next bullet that is “Purposes are assigned to applications” and given the previous statement “A purpose has associated set of personal information scopes.”
> “APIs or resources covered by the assigned scopes” -- doesn’t seem to be necessary as scopes can’t be associated with Apps without a specific purpose. Next bullet cover that

Yep, you are right. We can remove those bullets for now. It was inherited from another earlier document that was discussed before the creation of this WG...

**Comment by gmuratk** [comment]
> Each API operation could be protected with a different scope (if required). This way you can actually control which scopes are allowed for a particular purpose, and eventually have enough granularity to control access for each API operation. This is something that needs to be included in the API definition for each API operation, and should be analysed on a case-by-case basis.

In the case of API Roaming, a single Capability Consumer can have a relationship with one operator, which may have federation with other operators, thus can serve the subscribers of both networks.  The behavior (i.e. access to APIs) for a Developer may differ from one network to another.

**Comment by jpengar** [comment]
Fixed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/13 commit https://github.com/camaraproject/IdentityAndConsentManagement/pull/13/commits/4b761353f33ee263e98e8309c8fb698908401206 
@gmuratk Please take a look.
