### ISSUE TITLE
Propose the use of w3c DPV vocab as base to identify the purposes needed for consent management

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/IdentityAndConsentManagement#35]
**Problem description**
There is a general worry on how we could all align on the vocabulary of purposes such that it is interpreted in the same way by everyone.

**Possible evolution**
The proposal here is to use DPV vocabulary as our base https://w3c.github.io/dpv/dpv/#vocab-purpose 
We could leverage the expertise of the w3c community working group on this topic and do not need to start from scratch.
Feedback/alternatives from members is appreciated.

**Alternative solution**

**Additional context**

**Comment by jpengar** [comment]
From Telefónica's side, we are fully aligned on the use of DPV for the definition of "purposes".

**Comment by shilpa-padgaonkar** [comment]
can be closed with the above agreement and the fact that there are no other objections
