### ISSUE TITLE
Add missing details in authN-authZ doc

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/IdentityAndConsentManagement#45]
**Problem description**
This issue https://github.com/camaraproject/NumberVerification/issues/46 resolution should be piggy backed into the AuthN-AuthZ document 

**Expected action**
Extend AuthN-AuthZ doc with the details about network based authN

**Additional context**

**Comment by jpengar** [comment]
@shilpa-padgaonkar PR https://github.com/camaraproject/IdentityAndConsentManagement/pull/55 includes network-based auth information in the authN-authZ doc. It is ready for review.
