### ISSUE TITLE
What should be included as a part of a consent record?

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/IdentityAndConsentManagement#49]
**Problem description**
To be able to design a consent API, we need to detail out what a consent record should include. This issue is created as a question to gather feedback from the subproject members.

Some examples could be: ConsentStatus (granted/denied), Consent capture date+time, PersonalData  etc.

**Possible evolution**
We should be able to define a clear structure for consent.

**Alternative solution**

**Additional context**

**Comment by jpengar** [comment]
@shilpa-padgaonkar If it helps, and just as an example, below is how we currently model a consent record internally at Telefónica (not all fields may apply):

<img width="398" alt="image" src="https://github.com/camaraproject/IdentityAndConsentManagement/assets/1318242/6fd3d09b-f474-4330-a442-95274989eef9">

> NOTE: _We also want to add the application (with a client_id field or something like that)_.
> NOTE: _Fields like channel, reason, triggered_by... may be a bit more specific to Telefónica and not necessarily needed here_.

In any case, so far there is no need to expose a Consent API to third party clients as a CAMARA API with CRUD operations on consent records. Consent must be obtained through operator channels (there is no delegated consent) and only operators internally manage user consents (e.g. check if a consent record exists, create a new consent record if it is captured from the user, etc).
