### ISSUE TITLE
documentation/CAMARA-API-access-and-user-consent.md diagram update purpose/scope

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/IdentityAndConsentManagement#59]
**Problem description**
`documentation/CAMARA-API-access-and-user-consent.md` diagrams should be updated for POST/ authorize to use `scope` word instead of `purpose` word

**Expected action**
Update the diagram accordingly

**Additional context**
Discussed with TEF team Sept6th - agree on the principle - the issue is there to not forget this point for next update on the document.

**Comment by jpengar** [comment]
Thanks @bigludo7,

As discussed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/54, we can create a new PR once we have agreement on issue #32. This new PR will correct the flow accordingly and include the information about the agreed solution in the relevant doc sections.

**Comment by jpengar** [comment]
@bigludo7 https://github.com/camaraproject/IdentityAndConsentManagement/pull/75 FYI.

**Comment by bigludo7** [comment]
Thanks @jpengar - look good for me.
