### ISSUE TITLE
Front-end flow unauthenticated risk

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/IdentityAndConsentManagement#69]
A sister issue in OpenGateway: https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/issues/52

The first step of the front-end flow is a call from the end-user device to the Aggregator, at this point the Aggregator must work out which Operator to forward the request onto; in the flow it talks about using TelcoFinder.
TelcoFinder may not be free, and indeed when using MSISDN TelcoFinder which uses HLR or equivalent it is very unlikely to be free.
Having TelcoFinder (or any compute heavy task) in the Authorisation Code flow is not going to work, authorisation tokens must be 'free' to compute, otherwise there is a huge financial risk through DDoS style attacks.

**Comment by jpengar** [comment]
As per Yesterday's working group call (04/10), the issue will be discussed in the context of the GSMA technical stream, and anything that needs to be piggybacked into CAMARA will be raised later for everyone in CAMARA to review.
