### ISSUE TITLE
Front-end flow PII leakage?

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/IdentityAndConsentManagement#70]
As the consent check is within the unauthenticated auth code stage of the Authorisation Code flow, rather than in the access token stage, wouldn't it be possible to find out whether the user had consented to an operation or even had ever accessed another app? That would constitute PII leakage.

Could the consent check be moved into the access token stage, to avoid this?

**Comment by jpengar** [comment]
As per Yesterday's working group call (04/10), the issue will be discussed in the context of the GSMA technical stream, and anything that needs to be piggybacked into CAMARA will be raised later for everyone in CAMARA to review.

**Comment by chrishowell** [comment]
@jpengar are you going to bring the changes back into this project?

**Comment by chrishowell** [comment]
I'm intrigued - is consent meant to be collected in the authorisation code phase - so the access token wouldn't be obtainable until consent had been collected?
If that's the case, as an attacker I could trigger consent without authentication for all the ASP IDs :|

**Comment by palmerabollo** [comment]
Hi @chrishowell, this topic is actively being discussed in GSMA. You raised this issue regarding front-end flow PII leakage at https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/issues/53, and there is a pull request with an improvement at https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/pull/61 waiting for your input.
 
There is also this one at https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/issues/52, which is also related to the unauthenticated front-end flow. There is a proposal to optionally support RFC9101 (JWT-Secured Authorization Request) also waiting for your feedback.
 
The authorization code flow is standard, i.e. you can also trigger consent in a Google/Facebook/Twitter/... service.

**Comment by chrishowell** [comment]
I am not happy about this being discussed in the closed OpenGateway repo, authentication is a key part of CAMARA and needs to be discussed here too.

I have raised the issue in the open PR:
https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/pull/61/files#r1377367639

**Comment by palmerabollo** [comment]
I agree it would be great to open the GSMA repository to avoid duplicating issues. @MarkCornall, have you considered it?

In my opinion, we should define APIs in CAMARA and handle the integration with aggregators, operators, and other cross-cutting concerns, such as the authentication flows, in GSMA, where a working reference implementation exists.

The worst-case scenario is having the same issues duplicated in both repositories.
