### ISSUE TITLE
Recommendation for OIDC Java provider libraries

### ISSUE THREAD

**Issue by mhfoo** [camaraproject/IdentityAndConsentManagement#85]
Is there any recommendation for OIDC provider Java libraries to implement the following endpoints?
- CIBA
- Auth Code Grant

**Comment by palmerabollo** [comment]
These opensource (Apache 2) auth servers are Java-based and seem to support CIBA (and authorization code):
- Keycloak https://github.com/keycloak/keycloak/tree/23.0.0/services/src/main/java/org/keycloak/protocol/oidc/grants/ciba & https://www.grootan.com/casestudies/how-to-use-ciba-with-keycloak
- WSO2 https://ob.docs.wso2.com/en/latest/learn/ciba/#client-initiated-backchannel-authentication-ciba-flow

However, I can't personally recommend any of them as I haven't tried them myself. The [GSMA reference implementation](https://github.com/GSMA-Open-Gateway/opengateway-reference-implementation) contains a working Python version that might serve as a reference.

**Comment by AxelNennker** [comment]
I assume you know this: https://openid.net/developers/certified-openid-connect-implementations/

**Comment by jpengar** [comment]
@mhfoo I'm closing this topic as "completed". Of course we can reopen it if you think it is needed. But I'm trying to clean up the issue list a bit since it's growing fast.
