### ISSUE TITLE
Broke link to reference in CAMARA-API-access-and-user-consent

### ISSUE THREAD

**Issue by bhjelm** [camaraproject/IdentityAndConsentManagement#97]
**Problem description**
Link to referense [CAMARA Number Verification API](https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/CAMARA/uml_v0.3.jpg) is broken (404 page not found).

**Expected action**
Update the reference URL.

**Comment by jpengar** [comment]
Good catch. Thank you. Will be fixed.
